[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  NETLIFY_USE_YARN = "false"
  NPM_CONFIG_PRODUCTION = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Explicitly disable Next.js plugin
[[plugins]]
  # Empty plugins section to override auto-detection