# Site configuration
[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_CONFIG_PRODUCTION = "false"
  NETLIFY_USE_YARN = "false"
  # Force static site mode - no framework detection
  NETLIFY_FRAMEWORK = "static"
  NODE_OPTIONS = "--max-old-space-size=4096"

# SPA routing for React application
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200